Repository gradle/declarative-gradle, pull requests merged in 2024-07, with the labels that each got.

#103 Explicitly add software type model objects to extensions
  unified-prototype/gradle/wrapper/gradle-wrapper.properties
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
  unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaLibraryPlugin.java
  unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java
  unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpLibraryPlugin.java
  unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmLibraryPlugin.java
  unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/StandaloneSwiftApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/StandaloneSwiftLibraryPlugin.java
Labels: chore

#77 Add `cppLibrary` and `cppApplication` software types
  unified-prototype/README.md
  unified-prototype/cpp-util/build.gradle.dcl
  unified-prototype/cpp-util/src/main/cpp/cpp-util.cpp
  unified-prototype/cpp-util/src/main/public/cpp-util.h
  unified-prototype/settings.gradle.dcl
  unified-prototype/testbed-cpp-application/build.gradle.dcl
  unified-prototype/testbed-cpp-application/src/main/cpp/main.cpp
  unified-prototype/testbed-cpp-library/build.gradle.dcl
  unified-prototype/testbed-cpp-library/src/main/cpp/lib.cpp
  unified-prototype/testbed-swift-application/src/main/swift/main.swift
  unified-prototype/unified-plugin/plugin-common/build.gradle.kts
  unified-prototype/unified-plugin/plugin-cpp/build.gradle.kts
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/CppApplication.java
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/CppEcosystemPlugin.java
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/CppLibrary.java
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/HasCppTarget.java
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/StandaloneCppApplicationPlugin.java
  unified-prototype/unified-plugin/plugin-cpp/src/main/java/org/gradle/api/experimental/cpp/StandaloneCppLibraryPlugin.java
  unified-prototype/unified-plugin/settings.gradle.kts
Labels: enhancement

#102 Remove links to dedicated forum category
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#105 Update wrapper to latest Gradle nightly
  unified-prototype/gradle/wrapper/gradle-wrapper.properties
Labels: chore

#110 First stab at a software features reference page
  docs/reference/README.md
  docs/reference/glossary.md
  docs/reference/software-features.md
Labels: documentation

#111 Update wrapper and rename conventions -> defaults
  docs/reference/software-features.md
  unified-prototype/gradle/wrapper/gradle-wrapper.properties
  unified-prototype/settings.gradle.dcl
  unified-prototype/unified-plugin/plugin-android/src/integTest/groovy/org/gradle/api/experimental/android/AndroidLibrarySpec.groovy
Labels: chore
