Repository gradle/declarative-gradle, pull requests merged in 2024-05, with the labels that each got.

#37 CI build + deploy for unified prototype
  .teamcity/.gitignore
  .teamcity/.mvn/wrapper/MavenWrapperDownloader.java
  .teamcity/.mvn/wrapper/maven-wrapper.jar
  .teamcity/.mvn/wrapper/maven-wrapper.properties
  .teamcity/mvnw
  .teamcity/mvnw.cmd
  .teamcity/pom.xml
  .teamcity/settings.kts
  .teamcity/src/main/kotlin/common/features.kt
  .teamcity/src/main/kotlin/common/steps.kt
  .teamcity/src/main/kotlin/projects/DeclarativeGradleProject.kt
  .teamcity/src/main/kotlin/projects/unified/UnifiedPrototypeProject.kt
  .teamcity/src/main/kotlin/projects/unified/plugin/PluginProject.kt
  unified-prototype/unified-plugin/build-logic/src/main/kotlin/build-logic.publishing.gradle.kts
  unified-prototype/unified-plugin/build.gradle.kts
  unified-prototype/unified-plugin/plugin-android/build.gradle.kts
  unified-prototype/unified-plugin/plugin-jvm/build.gradle.kts
  unified-prototype/unified-plugin/plugin-kmp/build.gradle.kts
Labels: enhancement

#63 Getting Started with Declarative Gradle and Subsite
  .devcontainer/Dockerfile
  .devcontainer/LICENSE.txt
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
  .github/workflows/ci.yml
  .gitignore
  .vscode/settings.json
  README.md
  ROADMAP.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/android/README.md
  docs/assets/css/gradle.css
  docs/getting-started/README.md
  docs/images/logos/gradle-build-tool.svg
  docs/images/logos/gradle.svg
  mkdocs.yml
Labels: documentation

#68 Add disclaimer that the roadmap is in preview
  ROADMAP.md
Labels: documentation

#69 Add CD pipeline for the Declarative Gradle subsite
  .github/workflows/cd.yml
Labels: chore

#71 Remove "subsite" from the site description
  mkdocs.yml
Labels: documentation

#74 Add stub Java and Kotlin pages
  .devcontainer/requirements.txt
  docs/java/README.md
  docs/kotlin/README.md
  mkdocs.yml
Labels: documentation

#81 Add Release Drafter for changelog drafts
  .github/release-drafter.yml
  .github/workflows/changelog.yml
Labels: documentation, chore

#82 Allow manual Release Drafter triggering
  .github/workflows/changelog.yml
Labels: documentation, chore, skip-changelog

#83 Automatically replace NiA to Now in Android in the changelog drafts
  .github/release-drafter.yml
Labels: chore

#87 Fix build missing Swift on Linux and publishing plugins
  .teamcity/src/main/kotlin/projects/unified/UnifiedPrototypeProject.kt
  unified-prototype/unified-plugin/build.gradle.kts
  unified-prototype/unified-plugin/plugin-swift/build.gradle.kts
Labels: bug

#85 WIP - Support Protobuf in NiA
  unified-prototype/unified-plugin/gradle/libs.versions.toml
  unified-prototype/unified-plugin/plugin-android/build.gradle.kts
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AbstractAndroidSoftwarePlugin.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/ComposeSupport.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Protobuf.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/ProtobufDependencies.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Jacoco.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
  unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
Labels: enhancement
