Repository gradle/declarative-gradle, pull requests merged in 2024-11, with the labels that each got.

#139 Fix studio download links
  docs/getting-started/setup.md
Labels: bug

#143 Add preview deployment and deletion pipelines
  .github/workflows/ci.yml
  .github/workflows/preview-cleanup.yml
Labels: chore

#144 Use better Preview site destination
  .github/workflows/ci.yml
  .github/workflows/preview-cleanup.yml
Labels: chore

#141 Rework docs content for EAP2
  README.md
  docs/EAP2.md
  docs/README.md
  docs/ROADMAP.md
  docs/feedback.md
  docs/getting-started/README.md
  docs/getting-started/features.md
  docs/getting-started/samples.md
  docs/getting-started/setup.md
  docs/publications/2024-09-droidcon-nyc.md
  docs/publications/README.md
  docs/reference/README.md
  docs/reference/build-init.md
  docs/theme/main.html
  mkdocs.yml
Labels: documentation

#145 Fix TODO in Eclipse IDE setup doc
  docs/getting-started/setup.md
Labels: documentation

#146 Add note that Studio and Gradle Client are not notarized to setup documentation
  docs/getting-started/setup.md
Labels: documentation

#148 Add IntelliJ IDEA to documentation
  README.md
  docs/ROADMAP.md
  docs/getting-started/features.md
  docs/getting-started/setup.md
Labels: documentation
