Repository gradle/declarative-gradle, pull requests merged in 2025-01, with the labels that each got.

#155 Switch analytics to the unified engine
  docs/assets/js/google-tag-support.js
  docs/theme/main.html
  docs/theme/partials/integrations/analytics/custom.html
  mkdocs.yml
Labels: chore

#156 Clarify setup instructions around IDE setup
  docs/getting-started/setup.md
Labels: enhancement

#160 Android Studio regular nightlies now include support for Declarative
  docs/getting-started/setup.md
Labels: documentation
